### PR TITLE
make symlink ./latest

### PR DESCRIPTION
**Pull request by Crissov**
change Makefile to make `latest` always link to the latest version

### CODE REVIEW

**Comment by jgm** [comment]
I've been reluctant to do this because it will lead to broken links.
Someone browses to `/latest#fragment`, links to this, and then someone else later follows the link and lands on a later version.
A redirect is okay, and in fact there is already a redirect from `spec.commonmark.org/current` to the latest version.

**Comment by Crissov** [comment]
A symlink is simply the best I could come up with that is not a JS or HTML `meta` redirect

**Comment by jgm** [comment]
What's wrong with the current situation, where `/current` redirects you to the latest?

**Comment by Crissov** [comment]
Thatʼs a good thing. I just wish it used real, server-side HTTP 301 redirect, because the client-side solution currently used introduces a noticeable delay.

**Comment by jgm** [comment]
I don't think we can do that, because we're using GitHub pages for this part of the site.

**Pull request closed without merging**
